"""kielo_shared.vocab.scenario_source_type — Python mirror of
kielo-shared/vocab/scenariosourcetype.go.

Sweep ZQ Gap 3 (2026-06-03): cross-language SoT for the 5 canonical
convo.scenarios.source_type wire-string values. Mirrors the Go-side
typed alias + constants + iteration container at the wire-string
level.

## Architectural shape

  - ``ScenarioSourceType`` typed alias (str newtype) matching Go's
    ``vocab.ScenarioSourceType``
  - 5 ``Final[ScenarioSourceType]`` constants — byte-equivalent
    values to Go SoT
  - ``ALL_SCENARIO_SOURCE_TYPES`` ``FrozenSet`` iteration container
  - ``is_valid_scenario_source_type(s)`` validator helper

## Cross-language parity

The contract test at
``tests/contract/scenario_source_type_vocabulary_contract_test.go``
asserts every Go constant has a matching Python constant AND every
Python constant has a matching Go constant. Adding a new value in
one language without the other fails the gate.

## Engine producer call sites (Sweep ZQ Gap 3 migration)

  - kielolearn-engine/src/kielolearnengine/services/concept_hub_generator.py
    (2 sites — Sweep UUUUU canonical writer for ai_concept_hub_v1).

  - kielolearn-engine/src/kielolearnengine/api/endpoints/concept_hubs.py
    (1 site — reverse-lookup query parameter, Sweep UUUUU reader).
"""

from __future__ import annotations

from typing import Final, FrozenSet, NewType

# Typed alias mirroring Go-side vocab.ScenarioSourceType.
ScenarioSourceType = NewType("ScenarioSourceType", str)


# Production source types (3 — actively emitted by writers).
SCENARIO_SOURCE_TYPE_AI_CONCEPT_HUB_V1: Final[ScenarioSourceType] = ScenarioSourceType(
    "ai_concept_hub_v1"
)
"""Scenarios generated by the engine's concept-hub-generation flow.
Source_id is the grammar_concept_id; readers reverse-lookup via
/scenarios/by-source. Sole Python writer call site:
kielolearn-engine/.../services/concept_hub_generator.py."""

SCENARIO_SOURCE_TYPE_ADMIN_AUTHORED: Final[ScenarioSourceType] = ScenarioSourceType(
    "admin_authored"
)
"""Scenarios created via the admin tool. Source_id is typically NULL.
NO Python writer — only kielo-convo (Go) emits this."""

SCENARIO_SOURCE_TYPE_AI_SCENARIO_TEMPLATE_V1: Final[ScenarioSourceType] = (
    ScenarioSourceType("ai_scenario_template_v1")
)
"""Scenarios generated from an admin-authored template via the engine's
scenario-template-expansion flow. Reserved per Sweep UUUUU
pre-declaration discipline; no writer today."""


# External / migration-applied (1).
SCENARIO_SOURCE_TYPE_EXTERNAL_IMPORTED: Final[ScenarioSourceType] = ScenarioSourceType(
    "external_imported"
)
"""Scenarios imported from an external source (e.g. CSV bulk-import,
content-team pipeline). Reserved for future bulk-import flows."""


# Sentinel (1 — DEFAULT for rows where the canonical source is unknown).
SCENARIO_SOURCE_TYPE_UNKNOWN: Final[ScenarioSourceType] = ScenarioSourceType("unknown")
"""DEFAULT. Used by the V084 backfill on rows that pre-date the
source_type column. New writers should NEVER emit Unknown."""


# Iteration container — frozenset of all 5 canonical values.
# Used by:
#   - The Go↔Python parity contract test.
#   - The producer-scan + CHECK-parity contract tests.
#   - Operator tooling that needs to enumerate every source type.
ALL_SCENARIO_SOURCE_TYPES: FrozenSet[ScenarioSourceType] = frozenset(
    {
        SCENARIO_SOURCE_TYPE_AI_CONCEPT_HUB_V1,
        SCENARIO_SOURCE_TYPE_ADMIN_AUTHORED,
        SCENARIO_SOURCE_TYPE_AI_SCENARIO_TEMPLATE_V1,
        SCENARIO_SOURCE_TYPE_EXTERNAL_IMPORTED,
        SCENARIO_SOURCE_TYPE_UNKNOWN,
    }
)


def is_valid_scenario_source_type(value: str) -> bool:
    """Return True when value is one of the canonical wire strings.

    Use this at API request-validation layers to reject typo'd inputs
    at the application boundary (before they hit the V084 CHECK).
    """
    return ScenarioSourceType(value) in ALL_SCENARIO_SOURCE_TYPES


__all__ = [
    "ScenarioSourceType",
    "SCENARIO_SOURCE_TYPE_AI_CONCEPT_HUB_V1",
    "SCENARIO_SOURCE_TYPE_ADMIN_AUTHORED",
    "SCENARIO_SOURCE_TYPE_AI_SCENARIO_TEMPLATE_V1",
    "SCENARIO_SOURCE_TYPE_EXTERNAL_IMPORTED",
    "SCENARIO_SOURCE_TYPE_UNKNOWN",
    "ALL_SCENARIO_SOURCE_TYPES",
    "is_valid_scenario_source_type",
]
