// Package vocab — Sweep ZQ Gap 3 (2026-06-03)
//
// ScenarioSourceType typed-vocab SoT for the convo.scenarios.source_type
// column (V084 migration). 9th instance of the typed-vocab SoT pattern
// (alongside achievement.go, itemtype.go, kielo-shared/userlang/sources.go,
// kielo-shared/userlang/grantsource.go, kielo-shared/errors,
// kielo-shared/events/{cmswriterendpoint,outboxeventtype,publisheventtype}.go).
//
// Background:
// Sweep UUUUU (2026-06-02) shipped V084 with the source_type CHECK
// constraint pinning 5 values, but did NOT introduce a typed Go alias
// — writers across kielo-convo + kielolearn-engine emitted raw string
// literals at the producer sites. The wire-strings worked because the
// CHECK rejected typos at INSERT time, but a typo'd literal at any
// producer site would surface only at runtime via 23514 violation.
//
// Sweep ZQ Gap 3 closes this gap with the full Sweep-VVV-shape
// 3-anchor ship:
//
//   (a) Producer-side closed-set scan ✓ TestScenarioSourceTypeNoStaleLiteralsInProducer
//   (b) Go↔Python parity              ✓ TestScenarioSourceTypeGoPythonParity
//   (c) DB CHECK + OpenAPI enum parity ✓ TestScenarioSourceTypeMatchesV084CHECK
//
// (OpenAPI enum N/A today — source_type is response-only via the
// /scenarios/by-source query; no writeable enum list exists.)
//
// Adding a new ScenarioSourceType value:
//
//  1. Add the constant here with the canonical wire string.
//  2. Extend AllScenarioSourceTypes for iteration.
//  3. Add a sibling constant to kielo_shared/vocab/scenario_source_type.py.
//  4. Update the CHECK constraint in a new V0XX migration.
//  5. Update the producer call site to emit the typed constant.
//
// The 3 contract tests in tests/contract/
// scenario_source_type_vocabulary_contract_test.go enforce parity.
package vocab

// ScenarioSourceType is the typed alias writers pass into the
// convo.scenarios.source_type column. The wire format is a string
// so the column + JSON payloads stay stable across schema
// migrations; this Go type narrows the producer-side surface so a
// stray literal can't be silently accepted.
type ScenarioSourceType string

// String returns the wire string. Allows the typed constant to be
// used directly in fmt.Sprintf / log fields / SQL parameter binding
// without an explicit conversion at every call site.
func (s ScenarioSourceType) String() string {
	return string(s)
}

// Production source types (3 — actively emitted by writers).
const (
	// ScenarioSourceTypeAIConceptHubV1: scenarios generated by the
	// engine's concept-hub-generation flow. Source_id is the
	// grammar_concept_id; readers reverse-lookup via
	// /scenarios/by-source. Emitted at
	// kielolearn-engine/services/concept_hub_generator.py
	// (Sweep UUUUU canonical writer).
	ScenarioSourceTypeAIConceptHubV1 ScenarioSourceType = "ai_concept_hub_v1"

	// ScenarioSourceTypeAdminAuthored: scenarios created via the
	// admin tool (kielo-admin-ui ScenarioBuilder). Source_id is
	// typically NULL — there's no foreign reference. Emitted at
	// kielo-convo/go_orchestrator/internal/scenario/admin_repository.go
	// (the CreateScenarioRequest default when admin tooling omits
	// source_* fields).
	ScenarioSourceTypeAdminAuthored ScenarioSourceType = "admin_authored"

	// ScenarioSourceTypeAIScenarioTemplateV1: scenarios generated
	// from an admin-authored TEMPLATE via the engine's
	// scenario-template-expansion flow. Reserved per UUUUU
	// pre-declaration discipline; no writer today.
	ScenarioSourceTypeAIScenarioTemplateV1 ScenarioSourceType = "ai_scenario_template_v1"
)

// External / migration-applied (1).
const (
	// ScenarioSourceTypeExternalImported: scenarios imported from
	// an external source (e.g. CSV bulk-import, content-team
	// pipeline). Reserved for future bulk-import flows; no writer
	// today.
	ScenarioSourceTypeExternalImported ScenarioSourceType = "external_imported"
)

// Sentinel (1 — DEFAULT for rows where the canonical source is unknown).
const (
	// ScenarioSourceTypeUnknown: DEFAULT. Used by the V084 backfill
	// on rows that pre-date the source_type column. New writers
	// should NEVER emit Unknown — if you find yourself reaching for
	// it, the call site is missing a typed source.
	ScenarioSourceTypeUnknown ScenarioSourceType = "unknown"
)

// AllScenarioSourceTypes is the canonical iteration order. Used by:
//   - The contract test (ZQ Gap 3) to assert every literal in
//     producer code matches a value here.
//   - The CHECK-parity contract test to assert V084 CHECK matches
//     this list bidirectionally.
//   - The Go↔Python parity test to assert the Python mirror is
//     byte-equivalent.
var AllScenarioSourceTypes = []ScenarioSourceType{
	ScenarioSourceTypeAIConceptHubV1,
	ScenarioSourceTypeAdminAuthored,
	ScenarioSourceTypeAIScenarioTemplateV1,
	ScenarioSourceTypeExternalImported,
	ScenarioSourceTypeUnknown,
}

// IsKnownScenarioSourceType returns true when s is one of the
// canonical values. Used by repository-layer + service-layer
// validators to reject typo'd inputs at the application boundary
// (before they hit the V084 CHECK).
func IsKnownScenarioSourceType(s ScenarioSourceType) bool {
	for _, known := range AllScenarioSourceTypes {
		if known == s {
			return true
		}
	}
	return false
}
